import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { FAQ, GetFAQResults } from '../types'

const Home: NextPage<{ faqs: FAQ[] }> = ({faqs}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.myMain}>
        <div className={styles.titleBackground}>
          <h1 className={styles.title}>Frequently Asked Questions</h1>
        </div>
        {faqs.map(faq => {
          return (
            <div key={faq.id} className={styles.FAQCard}>
              <h1>{faq.attributes.Question}</h1>
              <p className={styles.answer}>{faq.attributes.Answer}</p>
            </div>
          )
        })}
        <p>
          If you have any futher questions, please contact us at  
          <a href="mailto:info@standfortrees.org"> info@standfortrees.org</a>
        </p>
      </main>

      {/* <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main> */}

      <footer className={styles.footer}>
        <a
          href="https://ethan-kaseff.github.io/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Developed by Ethan Kaseff
        </a>
      </footer>
    </div>
  )
}

export const getStaticProps: GetStaticProps = async (context) => {
  const res = await fetch('http://localhost:1337/api/faqs');
  const { data } : GetFAQResults = await res.json();

  return {
    props: {
      faqs: data,
    }
  }

}

export default Home
